<?xml version="1.0"?>

<robot name="servo" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass_palm" value="0.2" /> <!-- arbitrary value for mass -->
  <xacro:property name="mass_hand" value="20" /> <!-- arbitrary value for mass -->
  <xacro:property name="radius" value="0.05" /> <!-- Radii of the cylinder-->
  <xacro:property name="length1" value="0.1" /> <!-- seg42 -->
  <xacro:property name="length2" value="1" /> <!-- Rotator -->
  <xacro:property name="width" value="0.1" /> <!-- width of the beam -->
  <xacro:property name="offset" value="0" /> <!-- width of the beam -->
  <xacro:property name="spacing" value="0.25" /> <!-- width of the beam -->
  <xacro:property name="leftmost" value="-0.2" /> <!-- leftmost y cordinate of palm -->
  <xacro:property name="imr_width" value="0.173" /> <!-- index middle ring width -->
  <xacro:property name="l_width" value="0.15" /> <!-- little width -->
  <xacro:property name="x_width" value="0.10" />
  <xacro:property name="hand_height" value="3" /> <!-- little width -->
  <xacro:property name="hand_radius" value="0.30" /> <!-- little width -->

  <xacro:include filename="$(find servo_description)/urdf/servo.gazebo" />
  <xacro:include filename="$(find servo_description)/urdf/materials.xacro" />

<!--======================= Right Hand =================================== -->
  <link name="Right_upper">
    <collision>
      <origin xyz="0 0 ${hand_height/2}" rpy="0 0 0"/>
      <geometry>
         <cylinder length="${hand_height}" radius="${hand_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${hand_height/2}" rpy="0 0 0"/>
      <geometry>
         <cylinder length="${hand_height}" radius="${hand_radius}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 ${hand_height/2}" rpy="0 0 0"/>
      <mass value="${mass_hand*1000}"/>
      <inertia
          ixx="${1/12*mass_hand*hand_height*hand_height}" ixy="0.0" ixz="0.0"
          iyy="${1/12*mass_hand*hand_height*hand_height}" iyz="0.0"
          izz="${mass_hand*radius*radius}"/>
    </inertial>
  </link>

  <joint name="Right_hinge" type="revolute">
    <parent link="Right_upper"/>
    <child link="Right_lower"/>
    <origin xyz="${hand_radius} 0 ${hand_height}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.9"/>
    <limit effort="1000.0" lower="0" upper="1.57" velocity="10"/>
  </joint>

  <link name="Right_lower">
     <collision>
      <origin xyz="${-hand_radius} 0 ${hand_height/2}" rpy="0 0 0"/>
      <geometry>
         <cylinder length="${hand_height}" radius="${hand_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-hand_radius} 0 ${hand_height/2}" rpy="0 0 0"/>
      <geometry>
         <cylinder length="${hand_height}" radius="${hand_radius}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="${-hand_radius} 0 ${hand_height/2}" rpy="0 0 0"/>
      <mass value="${mass_hand}"/>
      <inertia
          ixx="${1/12*mass_hand*hand_height*hand_height}" ixy="0.0" ixz="0.0"
          iyy="${1/12*mass_hand*hand_height*hand_height}" iyz="0.0"
          izz="${mass_hand*radius*radius}"/>
    </inertial>
  </link>

<!-- ===============3 axis PALM joint ======================================= --> 
  
  <joint name="Right_palm_y" type="revolute"> 
    <parent link="Right_lower"/>
    <child link="Right_z_palmD"/>
    <origin xyz="${-hand_radius} ${-(leftmost+imr_width/2+spacing*3+l_width/2+leftmost)/2} ${hand_height}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="1000.0" lower="-1.57" upper="1.57" velocity="10"/>
  </joint>

  <link name="Right_z_palmD"> <!-- https://answers.ros.org/question/258420/ball-joint-in-urdf/ -->
    <inertial>
      <mass value="0.00025" />
      <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
    </inertial>
  </link>

  <joint name="Right_palm_z" type="revolute">
    <parent link="Right_z_palmD"/>
    <child link="Right_x_palmD"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
    <limit effort="1000.0" lower="-1.57" upper="1.57" velocity="10"/>
  </joint>

  <link name="Right_x_palmD">
    <inertial>
      <mass value="0.00025" />
      <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
    </inertial>
  </link>

  <joint name="Right_palm_x" type="revolute">
    <parent link="Right_x_palmD"/>
    <child link="Right_y_palmD"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
    <limit effort="1000.0" lower="-1.57" upper="1.57" velocity="10"/>
  </joint>

  <link name="Right_y_palmD">
    <inertial>
      <mass value="0.00025" />
      <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
    </inertial>
  </link>

  <joint name="Right_palm_d" type="fixed">
    <parent link="Right_y_palmD"/>
    <child link="Palm"/>
  </joint>



<!--========================PALM ========================================= -->
  <link name="Palm">
    <collision>
      <origin xyz="0 ${(leftmost+imr_width/2+spacing*3+l_width/2+leftmost)/2} 0.5" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width*2} ${(leftmost+imr_width/2+spacing*3+l_width/2+leftmost)+0.4} 1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${(leftmost+imr_width/2+spacing*3+l_width/2+leftmost)/2} 0.5" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width*2} ${(leftmost+imr_width/2+spacing*3+l_width/2+leftmost)+0.4} 1"/>
      </geometry>
      <material name="skin"/>
    </visual>

    <inertial>
      <origin xyz="0 ${(leftmost+imr_width/2+spacing*3+l_width/2+leftmost)/2} 0.5" rpy="0 0 0"/>
      <mass value="${mass_palm}"/>
      <inertia
          ixx="${mass_palm / 12.0 * (length1*length1 + length1*length1)}" ixy="0.0" ixz="0.0"
          iyy="${mass_palm / 12.0 * (length1*length1 + length1*length1)}" iyz="0.0"
          izz="${mass_palm / 12.0 * (length1*length1 + length1*length1)}"/>
    </inertial>
  </link>

<!--========================PALM JOINTS ========================================= -->

  <joint name="jointGT" type="fixed">
    <parent link="Palm"/>
    <child link="segt1"/>
    <origin xyz="0 ${leftmost-0.05} 0.3" rpy="0.52 0 0"/>
  </joint>

  <joint name="jointG1" type="fixed">
    <parent link="Palm"/>
    <child link="seg11"/>
    <origin xyz="0 ${leftmost+imr_width/2} 1" rpy="0 0 0"/>
  </joint>

  <joint name="jointG2" type="fixed">
    <parent link="Palm"/>
    <child link="seg21"/>
    <origin xyz="0 ${leftmost+imr_width/2+spacing} 1" rpy="0 0 0"/>
  </joint>

  <joint name="jointG3" type="fixed">
    <parent link="Palm"/>
    <child link="seg31"/>
    <origin xyz="0 ${leftmost+imr_width/2+spacing*2} 1" rpy="0 0 0"/>
  </joint>

  <joint name="jointG4" type="fixed">
    <parent link="Palm"/>
    <child link="seg41"/>
    <origin xyz="0 ${leftmost+imr_width/2+spacing*3} 1" rpy="0 0 0"/>
  </joint>

<!--====================== THUMB ===============================-->

  <link name="segt1">
    <collision>
      <origin xyz="0 0 ${0.15/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} 0.21 0.15"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${0.15/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} 0.21 0.15"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${0.15/2}" rpy="0 0 0"/>
      <mass value="${mass_palm}"/>
      <inertia
    ixx="${mass_palm / 12.0 * (length1*length1 + length1*length1)}" ixy="0.0" ixz="0.0"
    iyy="${mass_palm / 12.0 * (length1*length1 + length1*length1)}" iyz="0.0"
    izz="${mass_palm / 12.0 * (length1*length1 + length1*length1)}"/>
    </inertial>
  </link>

  <joint name="jointt1" type="revolute">
    <parent link="segt1"/>
    <child link="segt2"/>
    <origin xyz="${x_width/2} 0 0.15" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="1000.0" lower="0" upper="1.57" velocity="10"/>
  </joint>

  <link name="segt2">
    <collision>
      <origin xyz="${-x_width/2} 0 ${0.268/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} 0.21 0.268"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-x_width/2} 0 ${0.268/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} 0.21 0.268"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${-x_width/2} 0 ${0.268/2}" rpy="0 0 0"/>
      <mass value="${mass_palm}"/>
      <inertia
    ixx="${mass_palm / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
    iyy="${mass_palm / 12.0 * (length2*length2 + width*width)}" iyz="0.0"
    izz="${mass_palm / 12.0 * (width*width + length2*length2)}"/>
    </inertial>
  </link>

  <joint name="jointt2" type="revolute">
    <parent link="segt2"/>
    <child link="segt3"/>
    <origin xyz="0 0 ${0.268}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="1000.0" lower="0" upper="1.57" velocity="10"/>
  </joint>

  <link name="segt3">
    <collision>
      <origin xyz="${-x_width/2} 0 ${0.268/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} 0.21 0.268"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-x_width/2} 0 ${0.268/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} 0.21 0.268"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${-x_width/2} 0 ${0.268/2}" rpy="0 0 0"/>
      <mass value="${mass_palm}"/>
      <inertia
    ixx="${mass_palm / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
    iyy="${mass_palm / 12.0 * (length2*length2 + width*width)}" iyz="0.0"
    izz="${mass_palm / 12.0 * (width*width + length2*length2)}"/>
    </inertial>
  </link>

<!--====================== INDEX FINGER ===============================-->

  <link name="seg11">
    <collision>
      <origin xyz="0 0 ${0.268/2}" rpy="0 0 0"/>
      <geometry>
	       <box size="${x_width} ${imr_width} 0.268"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${0.268/2}" rpy="0 0 0"/>
      <geometry>
	       <box size="${x_width} ${imr_width} 0.268"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${0.268/2}" rpy="0 0 0"/>
      <mass value="${mass_palm}"/>
      <inertia
	  ixx="${mass_palm / 12.0 * (length1*length1 + length1*length1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass_palm / 12.0 * (length1*length1 + length1*length1)}" iyz="0.0"
	  izz="${mass_palm / 12.0 * (length1*length1 + length1*length1)}"/>
    </inertial>
  </link>

  <joint name="joint11" type="revolute">
    <parent link="seg11"/>
    <child link="seg12"/>
    <origin xyz="${x_width/2} 0 0.268" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="1000.0" lower="0" upper="1.57" velocity="10"/>
  </joint>

  <link name="seg12">
    <collision>
      <origin xyz="${-x_width/2} 0 ${0.268/2}" rpy="0 0 0"/>
      <geometry>
	       <box size="${x_width} ${imr_width} 0.268"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-x_width/2} 0 ${0.268/2}" rpy="0 0 0"/>
      <geometry>
	       <box size="${x_width} ${imr_width} 0.268"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${-x_width/2} 0 ${0.268/2}" rpy="0 0 0"/>
      <mass value="${mass_palm}"/>
      <inertia
	  ixx="${mass_palm / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
	  iyy="${mass_palm / 12.0 * (length2*length2 + width*width)}" iyz="0.0"
	  izz="${mass_palm / 12.0 * (width*width + length2*length2)}"/>
    </inertial>
  </link>

  <joint name="joint12" type="revolute">
    <parent link="seg12"/>
    <child link="seg13"/>
    <origin xyz="0 0 ${0.268}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="1000.0" lower="0" upper="1.57" velocity="10"/>
  </joint>

  <link name="seg13">
    <collision>
      <origin xyz="${-x_width/2} 0 ${0.268/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${imr_width} 0.268"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-x_width/2} 0 ${0.268/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${imr_width} 0.268"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${-x_width/2} 0 ${0.268/2}" rpy="0 0 0"/>
      <mass value="${mass_palm}"/>
      <inertia
    ixx="${mass_palm / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
    iyy="${mass_palm / 12.0 * (length2*length2 + width*width)}" iyz="0.0"
    izz="${mass_palm / 12.0 * (width*width + length2*length2)}"/>
    </inertial>
  </link>

<!--====================== MIDDLE FINGER ===============================-->

  <link name="seg21">
    <collision>
      <origin xyz="0 0 ${0.3/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${imr_width} 0.2"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${0.3/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${imr_width} 0.3"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${0.3/2}" rpy="0 0 0"/>
      <mass value="${mass_palm}"/>
      <inertia
    ixx="${mass_palm / 12.0 * (length1*length1 + length1*length1)}" ixy="0.0" ixz="0.0"
    iyy="${mass_palm / 12.0 * (length1*length1 + length1*length1)}" iyz="0.0"
    izz="${mass_palm / 12.0 * (length1*length1 + length1*length1)}"/>
    </inertial>
  </link>

  <joint name="joint21" type="revolute">
    <parent link="seg21"/>
    <child link="seg22"/>
    <origin xyz="${x_width/2} 0.0 0.3" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="1000.0" lower="0" upper="1.57" velocity="10"/>
  </joint>

  <link name="seg22">
    <collision>
      <origin xyz="${-x_width/2} 0 ${0.3/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${imr_width} 0.3"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-x_width/2} 0 ${0.3/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${imr_width} 0.3"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${-x_width/2} 0 ${0.3/2}" rpy="0 0 0"/>
      <mass value="${mass_palm}"/>
      <inertia
    ixx="${mass_palm / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
    iyy="${mass_palm / 12.0 * (length2*length2 + width*width)}" iyz="0.0"
    izz="${mass_palm / 12.0 * (width*width + length2*length2)}"/>
    </inertial>
  </link>

  <joint name="joint22" type="revolute">
    <parent link="seg22"/>
    <child link="seg23"/>
    <origin xyz="0 0 0.3" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="1000.0" lower="0" upper="1.57" velocity="10"/>
  </joint>

  <link name="seg23">
    <collision>
      <origin xyz="${-x_width/2} 0 ${0.3/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${imr_width} 0.3"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-x_width/2} 0 ${0.3/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${imr_width} 0.3"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${-x_width/2} 0 ${0.3/2}" rpy="0 0 0"/>
      <mass value="${mass_palm}"/>
      <inertia
    ixx="${mass_palm / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
    iyy="${mass_palm / 12.0 * (length2*length2 + width*width)}" iyz="0.0"
    izz="${mass_palm / 12.0 * (width*width + length2*length2)}"/>
    </inertial>
  </link>

<!--====================== RING FINGER ===============================-->

  <link name="seg31">
    <collision>
      <origin xyz="0 0 ${0.24/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${imr_width} 0.24"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${0.24/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${imr_width} 0.24"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${0.24/2}" rpy="0 0 0"/>
      <mass value="${mass_palm}"/>
      <inertia
    ixx="${mass_palm / 12.0 * (length1*length1 + length1*length1)}" ixy="0.0" ixz="0.0"
    iyy="${mass_palm / 12.0 * (length1*length1 + length1*length1)}" iyz="0.0"
    izz="${mass_palm / 12.0 * (length1*length1 + length1*length1)}"/>
    </inertial>
  </link>

  <joint name="joint31" type="revolute">
    <parent link="seg31"/>
    <child link="seg32"/>
    <origin xyz="${x_width/2} 0.0 0.24" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="1000.0" lower="0" upper="1.57" velocity="10"/>
  </joint>

  <link name="seg32">
    <collision>
      <origin xyz="${-x_width/2} 0 ${0.24/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${imr_width} 0.24"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-x_width/2} 0 ${0.24/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${imr_width} 0.24"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${-x_width/2} 0 ${0.24/2}" rpy="0 0 0"/>
      <mass value="${mass_palm}"/>
      <inertia
    ixx="${mass_palm / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
    iyy="${mass_palm / 12.0 * (length2*length2 + width*width)}" iyz="0.0"
    izz="${mass_palm / 12.0 * (width*width + length2*length2)}"/>
    </inertial>
  </link>

  <joint name="joint32" type="revolute">
    <parent link="seg32"/>
    <child link="seg33"/>
    <origin xyz="0 0 0.24" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="1000.0" lower="0" upper="1.57" velocity="10"/>
  </joint>

  <link name="seg33">
    <collision>
      <origin xyz="${-x_width/2} 0 ${0.24/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${imr_width} 0.24"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-x_width/2} 0 ${0.24/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${imr_width} 0.24"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${-x_width/2} 0 ${0.24/2}" rpy="0 0 0"/>
      <mass value="${mass_palm}"/>
      <inertia
    ixx="${mass_palm / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
    iyy="${mass_palm / 12.0 * (length2*length2 + width*width)}" iyz="0.0"
    izz="${mass_palm / 12.0 * (width*width + length2*length2)}"/>
    </inertial>
  </link>

<!--====================== LITTLE FINGER ===============================-->

  <link name="seg41">
    <collision>
      <origin xyz="0 0 ${0.15/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${l_width} 0.15"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${0.15/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${l_width} 0.15"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${0.15/2}" rpy="0 0 0"/>
      <mass value="${mass_palm}"/>
      <inertia
    ixx="${mass_palm / 12.0 * (length1*length1 + length1*length1)}" ixy="0.0" ixz="0.0"
    iyy="${mass_palm / 12.0 * (length1*length1 + length1*length1)}" iyz="0.0"
    izz="${mass_palm / 12.0 * (length1*length1 + length1*length1)}"/>
    </inertial>
  </link>

  <joint name="joint41" type="revolute">
    <parent link="seg41"/>
    <child link="seg42"/>
    <origin xyz="${x_width/2} 0.0 0.15" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="1000.0" lower="0" upper="1.57" velocity="10"/>
  </joint>

  <link name="seg42">
    <collision>
      <origin xyz="${-x_width/2} 0 ${0.15/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${l_width} 0.15"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-x_width/2} 0 ${0.15/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${l_width} 0.15"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${-x_width/2} 0 ${0.15/2}" rpy="0 0 0"/>
      <mass value="${mass_palm}"/>
      <inertia
    ixx="${mass_palm / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
    iyy="${mass_palm / 12.0 * (length2*length2 + width*width)}" iyz="0.0"
    izz="${mass_palm / 12.0 * (width*width + length2*length2)}"/>
    </inertial>
  </link>

  <joint name="joint42" type="revolute">
    <parent link="seg42"/>
    <child link="seg43"/>
    <origin xyz="0 0 0.15" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="1000.0" lower="0" upper="1.57" velocity="10"/>
  </joint>

  <link name="seg43">
    <collision>
      <origin xyz="${-x_width/2} 0 ${0.15/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${l_width} 0.15"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-x_width/2} 0 ${0.15/2}" rpy="0 0 0"/>
      <geometry>
         <box size="${x_width} ${l_width} 0.15"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${-x_width/2} 0 ${0.15/2}" rpy="0 0 0"/>
      <mass value="${mass_palm}"/>
      <inertia
    ixx="${mass_palm / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
    iyy="${mass_palm / 12.0 * (length2*length2 + width*width)}" iyz="0.0"
    izz="${mass_palm / 12.0 * (width*width + length2*length2)}"/>
    </inertial>
  </link>

<!-- ==================TRANSMISSION LINE =========================== -->
  <transmission name="trant1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="jointt1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motort1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="trant2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="jointt2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motort2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran11">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint11">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor11">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran12">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint12">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor12">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran21">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint21">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor21">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran22">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint22">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor22">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran31">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint31">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor31">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran32">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint32">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor32">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran41">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint41">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor41">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran42">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint42">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor42">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran_Right_hinge">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="Right_hinge">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_Right_hinge">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran_Right_palm_x">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="Right_palm_x">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_Right_palm_x">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran_Right_palm_z">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="Right_palm_z">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_Right_palm_z">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="tran_Right_palm_y">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="Right_palm_y">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_Right_palm_y">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


</robot>
