baby:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Trajectory Controllers ---------------------------------------
  Hand_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - Right_hand_y
      - Right_hand_x
      - Right_hand_z
      - Right_palm_y
      - Right_palm_x
      - Right_hinge
      - Left_hand_y
      - Left_hand_x
      - Left_hand_z
      - Left_palm_y
      - Left_palm_x
      - Left_hinge
    
    gains: 
      Right_hand_y: {p: 40000, d: 0, i: 0, i_clamp: 0}
      Right_hand_x: {p: 40000, d: 0, i: 0, i_clamp: 0}
      Right_hand_z: {p: 40000, d: 0, i: 0, i_clamp: 0}
      Right_palm_y: {p: 40000, d: 0, i: 0, i_clamp: 0}
      Right_palm_x: {p: 40000, d: 0, i: 0, i_clamp: 0}
      Right_hinge: {p: 40000, d: 0, i: 0, i_clamp: 0}
      Left_hand_y: {p: 40000, d: 0, i: 0, i_clamp: 0}
      Left_hand_z: {p: 40000, d: 0, i: 0, i_clamp: 0}
      Left_hand_x: {p: 40000, d: 0, i: 0, i_clamp: 0}
      Left_palm_y: {p: 40000, d: 0, i: 0, i_clamp: 0}
      Left_palm_x: {p: 40000, d: 0, i: 0, i_clamp: 0}
      Left_hinge: {p: 40000, d: 0, i: 0, i_clamp: 0}

  Leg_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - Right_leg_y
      - Left_leg_y
      - Right_leg_hinge
      - Left_leg_hinge
      - Right_foot_y
      - Left_foot_y
      
    gains: 
      Right_leg_y: {p: 40000,  d: 0, i: 0, i_clamp: 0}
      Left_leg_y: {p: 40000,  d: 0, i: 0, i_clamp: 0}
      Right_leg_hinge: {p: 40000,  d: 0, i: 0, i_clamp: 0}
      Left_leg_hinge: {p: 40000,  d: 0, i: 0, i_clamp: 0}
      Right_foot_y: {p: 40000,  d: 0, i: 0, i_clamp: 0}
      Left_foot_y: {p: 40000,  d: 0, i: 0, i_clamp: 0}
  #Leg controllers

  Right_leg_y_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_leg_y
    pid: {p: 40000.0, i: 0.0, d: 0.0}

  Left_leg_y_position_controller:
    type: effort_controllers/JointPositionController
    joint: Left_leg_y
    pid: {p: 40000.0, i: 0.0, d: 0.0}

  Right_leg_hinge_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_leg_hinge
    pid: {p: 40000.0, i: 0.0, d: 0.0}

  Left_leg_hinge_position_controller:
    type: effort_controllers/JointPositionController
    joint: Left_leg_hinge
    pid: {p: 40000.0, i: 0.0, d: 0.0}

  Right_foot_y_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_foot_y
    pid: {p: 40000.0, i: 0.0, d: 0.0}

  Left_foot_y_position_controller:
    type: effort_controllers/JointPositionController
    joint: Left_foot_y
    pid: {p: 40000.0, i: 0.0, d: 0.0}

  # Right_leg_x_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: Right_leg_x
  #   pid:  {p: 40000, i: 0, d: 0}

  # Right_leg_z_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: Right_leg_z
  #   pid:  {p: 40000, i: 0, d: 0}  

  # Left_leg_x_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: Left_leg_x
  #   pid:  {p: 40000, i: 0, d: 0}

  # Left_leg_z_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: Left_leg_z
  #   pid:  {p: 40000, i: 0, d: 0}    

  #Neck controller   
  Neck_y_position_controller:
    type: position_controllers/JointPositionController
    joint: Neck_y_joint
    pid: {p: 40000.0, i: 0.0, d: 0.0}

  Head_x_position_controller:
    type: position_controllers/JointPositionController
    joint: Head_x_joint
    pid: {p: 40000.0, i: 0.0, d: 0.0}

  Head_z_position_controller:
    type: position_controllers/JointPositionController
    joint: Head_z_joint
    pid: {p: 40000.0, i: 0.0, d: 0.0}
  
  #Right Hand controllers
  Right_hand_y_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_hand_y
    pid: {p: 40000.0, i: 0.0, d: 0.0}

  Right_hand_x_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_hand_x
    pid:  {p: 40000, i: 0, d: 0}

  Right_hand_z_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_hand_z
    pid:  {p: 40000, i: 0, d: 0}
 
  Right_hinge_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_hinge
    pid:  {p: 40000, i: 0, d: 0}

  Right_palm_y_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_palm_y
    pid:  {p: 40000, i: 0, d: 0}
  
  Right_palm_x_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_palm_x
    pid:  {p: 40000, i: 0, d: 0}

  #Left Hand controllers

  Left_hand_y_position_controller:
    type: effort_controllers/JointPositionController
    joint: Left_hand_y
    pid: {p: 40000.0, i: 0.0, d: 0.0}

  Left_hand_x_position_controller:
    type: effort_controllers/JointPositionController
    joint: Left_hand_x
    pid:  {p: 40000, i: 0, d: 0}

  Left_hand_z_position_controller:
    type: effort_controllers/JointPositionController
    joint: Left_hand_z
    pid:  {p: 40000, i: 0, d: 0}

  Left_hinge_position_controller:
    type: effort_controllers/JointPositionController
    joint: Left_hinge
    pid: {p: 40000, i: 0.0, d: 0.0}

  Left_palm_y_position_controller:
    type: effort_controllers/JointPositionController
    joint: Left_palm_y
    pid: {p: 40000.0, i: 0.0, d: 0.0}
 
  Left_palm_x_position_controller:
    type: effort_controllers/JointPositionController
    joint: Left_palm_x
    pid:  {p: 40000, i: 0, d: 0} 

  #Palm Controller
  Right_jointt1_position_controller:
    type: position_controllers/JointPositionController
    joint: Right_jointt1
    pid:  {p: 40000, i: 0, d: 0} 

  Right_jointt2_position_controller:
    type: position_controllers/JointPositionController
    joint: Right_jointt2
    pid:  {p: 40000, i: 0, d: 0} 

  Right_joint11_position_controller:
    type: position_controllers/JointPositionController
    joint: Right_joint11
    pid:  {p: 40000, i: 0, d: 0} 

  Right_joint12_position_controller:
    type: position_controllers/JointPositionController
    joint: Right_joint12
    pid:  {p: 40000, i: 0, d: 0} 

  Right_joint21_position_controller:
    type: position_controllers/JointPositionController
    joint: Right_joint21
    pid:  {p: 40000, i: 0, d: 0} 

  Right_joint22_position_controller:
    type: position_controllers/JointPositionController
    joint: Right_joint22
    pid:  {p: 40000, i: 0, d: 0} 

  Right_joint31_position_controller:
    type: position_controllers/JointPositionController
    joint: Right_joint31
    pid:  {p: 40000, i: 0, d: 0} 

  Right_joint32_position_controller:
    type: position_controllers/JointPositionController
    joint: Right_joint32
    pid:  {p: 40000, i: 0, d: 0} 

  Right_joint41_position_controller:
    type: position_controllers/JointPositionController
    joint: Right_joint41
    pid:  {p: 40000, i: 0, d: 0} 

  Right_joint42_position_controller:
    type: position_controllers/JointPositionController
    joint: Right_joint42
    pid:  {p: 40000, i: 0, d: 0} 

  #Palm Controller
  Left_jointt1_position_controller:
    type: position_controllers/JointPositionController
    joint: Left_jointt1
    pid:  {p: 40000, i: 0, d: 0} 

  Left_jointt2_position_controller:
    type: position_controllers/JointPositionController
    joint: Left_jointt2
    pid:  {p: 40000, i: 0, d: 0} 

  Left_joint11_position_controller:
    type: position_controllers/JointPositionController
    joint: Left_joint11
    pid:  {p: 40000, i: 0, d: 0} 

  Left_joint12_position_controller:
    type: position_controllers/JointPositionController
    joint: Left_joint12
    pid:  {p: 40000, i: 0, d: 0} 

  Left_joint21_position_controller:
    type: position_controllers/JointPositionController
    joint: Left_joint21
    pid:  {p: 40000, i: 0, d: 0} 

  Left_joint22_position_controller:
    type: position_controllers/JointPositionController
    joint: Left_joint22
    pid:  {p: 40000, i: 0, d: 0} 

  Left_joint31_position_controller:
    type: position_controllers/JointPositionController
    joint: Left_joint31
    pid:  {p: 40000, i: 0, d: 0} 

  Left_joint32_position_controller:
    type: position_controllers/JointPositionController
    joint: Left_joint32
    pid:  {p: 40000, i: 0, d: 0} 

  Left_joint41_position_controller:
    type: position_controllers/JointPositionController
    joint: Left_joint41
    pid:  {p: 40000, i: 0, d: 0} 

  Left_joint42_position_controller:
    type: position_controllers/JointPositionController
    joint: Left_joint42
    pid:  {p: 40000, i: 0, d: 0} 

  