servo:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  jointt1_position_controller:
    type: effort_controllers/JointPositionController
    joint: jointt1
    pid: {p: 100.0, i: 0.01, d: 10.0}

  jointt2_position_controller:
    type: effort_controllers/JointPositionController
    joint: jointt2
    pid: {p: 100.0, i: 0.01, d: 10.0}



  joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint11
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint12
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint21_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint21
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint22_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint22
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint31_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint31
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint32_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint32
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint41_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint41
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint42_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint42
    pid: {p: 100.0, i: 0.01, d: 10.0}

